# Generated by Django 4.2.4 on 2024-07-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_alter_taskmodel_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
